services:
  app_banco:
    build: .
    container_name: app_banco
    restart: always
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    networks:
      - backend

  nginx_banco:
    image: nginx:alpine
    container_name: nginx_banco
    restart: always
    ports:
      - "8003:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/app/media:ro
      - ./staticfiles:/app/staticfiles:ro
    networks:
      - backend
    depends_on:
      - app_banco

  onlyoffice:
    image: onlyoffice/documentserver:9.4.0
    container_name: onlyoffice
    restart: always
    ports:
      - "8004:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=eeyuiJmUl1XI3FUz5gEf
      - VERIFY_SSL_ON_SERVER=false
    networks:
      - backend

networks:
  backend:
    external: true