# Generated by Django 5.2 on 2025-05-07 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0002_alter_pregunta_contenido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='universidad',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='universidad',
            name='cursos',
            field=models.ManyToManyField(related_name='universidades', to='Preguntas.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.curso'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.tema'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.universidad'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Preguntas.userprofile'),
        ),
    ]
