# Generated by Django 5.2.12 on 2026-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0015_pregunta_tiene_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
