# Generated by Django 5.2.12 on 2026-03-12 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0016_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='solucion_archivo',
            field=models.FileField(blank=True, help_text='Archivo .docx con las imágenes y texto de la resolución', null=True, upload_to='soluciones/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.FileField(help_text='Archivo .docx con el enunciado de la pregunta', upload_to='preguntas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', help_text='Respuesta correcta resaltada en amarillo en el Word', max_length=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tiene_solucion',
            field=models.BooleanField(default=False, help_text='Se activa automáticamente si se detecta @SOLUCION@'),
        ),
    ]
