# Generated by Django 5.2.12 on 2026-03-17 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0017_pregunta_solucion_archivo_alter_pregunta_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.FileField(upload_to='preguntas/', validators=[django.core.validators.FileExtensionValidator(['docx'])]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='solucion_archivo',
            field=models.FileField(blank=True, null=True, upload_to='soluciones/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tiene_solucion',
            field=models.BooleanField(default=False),
        ),
    ]
