# Generated by Django 5.2.12 on 2026-03-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0018_alter_pregunta_contenido_alter_pregunta_nivel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_preguntas', models.PositiveIntegerField()),
                ('tiempo_minutos', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.curso')),
                ('temas', models.ManyToManyField(to='Preguntas.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PracticaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_alumno', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Preguntas.practica')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.pregunta')),
            ],
            options={
                'unique_together': {('practica', 'pregunta')},
            },
        ),
    ]
