# Generated by Django 5.2.12 on 2026-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0019_practica_practicapregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('admin', 'Admin'), ('user', 'User'), ('estudiante', 'Estudiante')], default='estudiante', max_length=20),
        ),
    ]
