# Generated by Django 5.2.12 on 2026-03-25 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0020_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
