# Generated by Django 5.2.12 on 2026-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0021_practica_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='aciertos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practica',
            name='blancos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practica',
            name='errores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
